# Data exploration

Data source [link](https://www.kaggle.com/datasets/andrewmvd/spotify-playlists)

In [2]:
import pandas as pd

df = pd.read_csv('../../data/spotify_dataset.csv', on_bad_lines='skip')
df.columns=["user","artist","track","playlist"]
df.head()

,user,artist,track,playlist
0,9cc0cfd4d7d7885102480dd99e7a90d6,Elvis Costello,(The Angels Wanna Wear My) Red Shoes,HARD ROCK 2010
1,9cc0cfd4d7d7885102480dd99e7a90d6,Elvis Costello & The Attractions,"(What's So Funny 'Bout) Peace, Love And Unders...",HARD ROCK 2010
2,9cc0cfd4d7d7885102480dd99e7a90d6,Tiffany Page,7 Years Too Late,HARD ROCK 2010
3,9cc0cfd4d7d7885102480dd99e7a90d6,Elvis Costello & The Attractions,Accidents Will Happen,HARD ROCK 2010
4,9cc0cfd4d7d7885102480dd99e7a90d6,Elvis Costello,Alison,HARD ROCK 2010

# Data exploration

## Questions

- How many artists do we have?
  - 289,821
- How many users do we have?
  - 15,918
- How many playlists do users have?
  - 15, on average

In [ ]:
# number of artists
df['artist'].nunique()

289821

In [ ]:
# number of users
df['user'].nunique()

15918

In [5]:
# avg number of playlists per user
playlist_user = df[['user', 'playlist']].drop_duplicates()
playlist_user.head()

                                 user        playlist
0    9cc0cfd4d7d7885102480dd99e7a90d6  HARD ROCK 2010
67   9cc0cfd4d7d7885102480dd99e7a90d6        IOW 2012
104  07f0fc3be95dcd878966b1f9572ff670            2080
114  07f0fc3be95dcd878966b1f9572ff670            C418
148  07f0fc3be95dcd878966b1f9572ff670       Chill out

In [6]:
playlist_user_counts = playlist_user.groupby('user')['playlist'].count()
playlist_user_counts.head()

user
00055176fea33f6e027cd3302289378b     1
0007f3dd09c91198371454c608d47f22     3
000b0f32b5739f052b9d40fcc5c41079     7
000c11a16c89aa4b14b328080f5954ee    20
00123e0f544dee3ab006aa7f1e5725a7    33
Name: playlist, dtype: int64

In [7]:
playlist_user_counts.mean()

14.562382208820203